language: python
branches:
  only:
  - master
install:
- pip install -r requirements.txt
script:
- make clean
- make github_travis_push
- make clean
- travis_wait 30 make aws
#deploy:
#    provider: s3
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key: $AWS_SECRET_KEY
#    bucket: visibilityspots.org
#    region: eu-west-1
#    skip_cleanup: true
#    local-dir: output
#    acl: public_read
#    detect_encoding: true
notifications:
  email:
    on_success: change
    on_failure: change
env:
  global:
    secure: A16p9Y0BVoqmdyIKqSCnEeWuz+iLtaUgr2moxdZKm+mQ/YMsKq4JlPHC1UfD4/ea+zVMxdv0ojmMa94oqF/YE23vsTbbg0dh6CbwLgklj7ztl48XwYYa+rx2BVhQkrMHwEC1jEHEEAnoRcWRcyEy1qIfL3SAG4cFYXSDZjOu08c=
