language: python
branches:
  only:
  - master
install:
- pip install -r requirements.txt
script:
- make clean
- make github-travis
- make clean
- make aws-create
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: visibilityspots.org
  region: eu-west-1
  skip_cleanup: true
  local-dir: output
  acl: public_read
  cache_control: "max-age=21600"
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
notifications:
  email:
    on_success: change
    on_failure: change
env:
  global:
    secure: A16p9Y0BVoqmdyIKqSCnEeWuz+iLtaUgr2moxdZKm+mQ/YMsKq4JlPHC1UfD4/ea+zVMxdv0ojmMa94oqF/YE23vsTbbg0dh6CbwLgklj7ztl48XwYYa+rx2BVhQkrMHwEC1jEHEEAnoRcWRcyEy1qIfL3SAG4cFYXSDZjOu08c=
