sudo: false
language: python

branches:
  only:
    - master

before_install:
  - shopt -s dotglob && mkdir content && mv !(content|id_travis*) content
  - openssl aes-256-cbc -K $encrypted_0ec63286c3a4_key -iv $encrypted_0ec63286c3a4_iv
    -in id_travis.enc -out id_travis -d
  - chmod 0600 id_travis
install:
  - pip install pelican ghp-import

before_script:
  - echo -e "Host ssh.visibilityspots.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
  - nosetests
  - ls -latr

after_success:
  - ssh -i id_travis visibilityspots.com@ssh.visibilityspots.com 'whoami'

notifications:
  email:
    - travis-blog@visibilityspots.com
