language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import
script: nosetests
before_install:
- openssl aes-256-cbc -K $encrypted_0ec63286c3a4_key -iv $encrypted_0ec63286c3a4_iv
  -in id_travis.enc -out id_travis -d
