#!/usr/bin/env python
# -*- coding: utf-8 -*- #
from __future__ import unicode_literals

import os
import sys
sys.path.append(os.curdir)
from pelicanconf import *

SITEURL = 'https://visibilityspots.org'
RELATIVE_URLS = False

GOOGLE_ANALYTICS = 'UA-66404450-1'

FEED_ALL_ATOM = 'feeds/all.atom.xml'
FEED_ALL_RSS = 'feeds/all.rss.xml'
CATEGORY_FEED_ATOM = "feeds/{slug}.atom.xml"
CATEGORY_FEED_RSS = "feeds/{slug}.rss.xml"

DELETE_OUTPUT_DIRECTORY = True

DISQUS_SITENAME = "visibilityspots"
ARTICLE_EXCLUDES = ['drafts']

CUSTOM_FOOTER = '<a href="http://creativecommons.org/licenses/by-nc/2.0/be/deed.nl">License</a> | 2009 - 2025 <a href="https://visibilityspots.org">visibilityspots.org</a> | Generated by <a href="http://getpelican.com/" target="pelican">Pelican</a> | Hosted at <a href="https://aws.amazon.com/s3/" target="amazon">Amazon S3</a> | <a href="https://visibilityspots.org/feeds/all.atom.xml" rel="alternate">Atom</a> feed'
