#!/usr/bin/env python
# -*- coding: utf-8 -*- #
from __future__ import unicode_literals

import os
import sys
sys.path.append(os.curdir)
from pelicanconf import *

SITEURL = "https://visibilityspots.github.io/blog"
RELATIVE_URLS = False

FEED_ALL_ATOM = 'feeds/all.atom.xml'
FEED_ALL_RSS = 'feeds/all.rss.xml'
CATEGORY_FEED_ATOM = 'feeds/%s.atom.xml'
CATEGORY_FEED_RSS = 'feeds/%s.rss.xml'

DELETE_OUTPUT_DIRECTORY = True

DISQUS_SITENAME = "visibilityspots"
ARTICLE_EXCLUDES = ['drafts']

CUSTOM_FOOTER = '<a href="http://creativecommons.org/licenses/by-nc/2.0/be/deed.nl">License</a> | 2009 - 2019 <a href="https://visibilityspots.github.io/blog">visibilityspots.github.io/blog</a> | Generated by <a href="http://getpelican.com/" target="pelican">Pelican</a> | Hosted at <a href="https://pages.github.com/" target="github pages">github pages</a> | <a href="https://visibilityspots.github.io/blog/feeds/all.atom.xml" rel="alternate">Atom</a> feed'
