[input]
html_selector = "main"
base_directory = "/home/runner/work/blog/blog/content"

[[input.files]]
path = "pages/contact.rst"
url = "/pages/contact.html"
title = "Contact"

[[input.files]]
path = "pages/profile.md"
url = "/pages/profile.html"
title = "Profile"

[[input.files]]
path = "pages/projects.rst"
url = "/pages/projects.html"
title = "Projects"

[[input.files]]
path = "pages/tools.md"
url = "/pages/tools.html"
title = "Tools"

[[input.files]]
path = "articles/containers/traefik-a-rating.md"
url = "/traefik-ssl-grading.html"
title = "Traefik SSL grading"

[[input.files]]
path = "articles/containers/traefik.md"
url = "/traefik-nomad-route53.html"
title = "Traefik nomad route53 setup"

[[input.files]]
path = "articles/other/planespotting.md"
url = "/planespotting.html"
title = "Plane spotting on a nomad cluster"

[[input.files]]
path = "articles/linux/httpd-semaphores.md"
url = "/httpd-semaphores.html"
title = "Httpd semaphores"

[[input.files]]
path = "articles/other/piaware.md"
url = "/piaware.html"
title = "Piaware on a nomad cluster"

[[input.files]]
path = "articles/containers/nomad-arm-cluster.md"
url = "/nomad-arm-cluster.html"
title = "Nomad ARM cluster"

[[input.files]]
path = "articles/linux/compute-sticks.md"
url = "/compute-sticks.html"
title = "ArchLinux on intel compute stick"

[[input.files]]
path = "articles/containers/nomad-local-development.md"
url = "/nomad-local-development.html"
title = "Nomad local development"

[[input.files]]
path = "articles/linux/bios-upgrade-lenovo.md"
url = "/bios-upgrade-lenovo.html"
title = "BIOS upgrade lenovo archlinux"

[[input.files]]
path = "articles/linux/print-server.md"
url = "/print-server.html"
title = "Archlinux ARM pi zero cups network print server"

[[input.files]]
path = "articles/linux/ansible-archlinux-update.md"
url = "/ansible-archlinux-upgrade.html"
title = "Ansible-playbook archlinux upgrade"

[[input.files]]
path = "articles/containers/prometheus-export.md"
url = "/prometheus-export-import.html"
title = "Prometheus export/import"

[[input.files]]
path = "articles/containers/prometheus-consul.md"
url = "/prometheus-consul.html"
title = "Prometheus consul service discovery"

[[input.files]]
path = "articles/containers/dockerized-doh.md"
url = "/dockerized-cloudflared-pi-hole.html"
title = "dockerized DNS over HTTPS using pi-hole through cloudflared proxy-dns"

[[input.files]]
path = "articles/linux/nrpe-troubleshooting.md"
url = "/nrpe-troubleshooting.html"
title = "NRPE troubleshooting"

[[input.files]]
path = "articles/containers/docker-ansible-tests.md"
url = "/test-ansible-playbooks.html"
title = "Test ansible playbooks with docker"

[[input.files]]
path = "articles/containers/jenkins-docker-pipeline.md"
url = "/jenkins-docker-pipeline.html"
title = "Jenkins docker-pipeline"

[[input.files]]
path = "articles/automation/gradle-build.md"
url = "/gradle-build.html"
title = "Jenkins gradle build succeeded with failure"

[[input.files]]
path = "articles/containers/nexus-oss-repository.md"
url = "/nexus-oss-repository-manager.html"
title = "Nexus OSS repository manager"

[[input.files]]
path = "articles/containers/dockerized-jenkins.md"
url = "/dockerized-jenkins.html"
title = "Dockerized jenkins master/slave setup"

[[input.files]]
path = "articles/containers/docker-openstackclient-kilo.md"
url = "/docker-openstackclient-kilo.html"
title = "Docker openstackclient-kilo container"

[[input.files]]
path = "articles/linux/pelican-travis.md"
url = "/pelican-travis.html"
title = "Auto deploy webpage using pelican and travis"

[[input.files]]
path = "articles/cloud/openstack-mtu-change.md"
url = "/openstack-mtu.html"
title = "Openstack Kilo change MTU till the VM it's tap interface"

[[input.files]]
path = "articles/cloud/s3stat.md"
url = "/s3stat.html"
title = "S3stat"

[[input.files]]
path = "articles/linux/wireless-bond-archlinux.md"
url = "/wireless-bond-archlinux.html"
title = "wireless bond archlinux arm"

[[input.files]]
path = "articles/cloud/aws-migration.md"
url = "/aws-migration.html"
title = "AWS migration"

[[input.files]]
path = "articles/cloud/openstack-static-ip.md"
url = "/openstack-static-ip.html"
title = "Openstack static ip"

[[input.files]]
path = "articles/cloud/openstack-live-migration.md"
url = "/openstack-live-migration.html"
title = "Openstack live-migration"

[[input.files]]
path = "articles/cloud/openstack-layer2.md"
url = "/openstack-layer2.html"
title = "Openstack layer2"

[[input.files]]
path = "articles/linux/sms-wall.md"
url = "/social-media-wall.html"
title = "SMS twitter wall"

[[input.files]]
path = "articles/puppet/vagrant-puppet-setup.md"
url = "/vagrant-puppet-setup.html"
title = "Vagrant puppet setup"

[[input.files]]
path = "articles/cloud/openstack-neutron.md"
url = "/vlan-flat-neutron-provider.html"
title = "Openstack vlan based flat neutron network provider"

[[input.files]]
path = "articles/linux/btrfs-mount-error.md"
url = "/btrfs-mount-issue.html"
title = "Btrfs mount issue"

[[input.files]]
path = "articles/linux/simple-monitoring.md"
url = "/simple-monitoring.html"
title = "Simple monitoring"

[[input.files]]
path = "articles/linux/vagrant-setup.md"
url = "/vagrant-setup.html"
title = "vagrant-setup"

[[input.files]]
path = "articles/linux/github-mirror.md"
url = "/github-mirroring.html"
title = "Github mirroring"

[[input.files]]
path = "articles/puppet/ansible-orchestration.md"
url = "/ansible-orchestration.html"
title = "Ansible orchestration"

[[input.files]]
path = "articles/linux/wifi-qr-code.md"
url = "/wifi-qr-code.html"
title = "Wifi QR code"

[[input.files]]
path = "articles/linux/rsnapshot-backup.md"
url = "/rsnapshot-backup.html"
title = "Rsnapshot backup"

[[input.files]]
path = "articles/home-automation/nest.md"
url = "/nest.html"
title = "Nest"

[[input.files]]
path = "articles/linux/raspberry-pi.md"
url = "/raspberry-pi.html"
title = "Raspberry pi setup"

[[input.files]]
path = "articles/linux/octoprint.md"
url = "/octoprint.html"
title = "Octoprint"

[[input.files]]
path = "articles/linux/pakiti.md"
url = "/pakiti.html"
title = "Pakiti setup"

[[input.files]]
path = "articles/linux/mkdocs.md"
url = "/mkdocs.html"
title = "Mkdocs documentation"

[[input.files]]
path = "articles/conferences/CloudCollab-Amsterdam.rst"
url = "/cloudcollab-amsterdam.html"
title = "CloudCollab Amsterdam #CCCEU13"

[[input.files]]
path = "articles/linux/git-server.rst"
url = "/git-server.html"
title = "Git server"

[[input.files]]
path = "articles/linux/dashing.rst"
url = "/dashing.html"
title = "Dashing"

[[input.files]]
path = "articles/conferences/LinuxCon-Edingburgh.rst"
url = "/linuxcon-edinburgh.html"
title = "LinuxCon Edinburgh"

[[input.files]]
path = "articles/linux/cpan-packages.rst"
url = "/cpan-rpm-packages.html"
title = "CPAN rpm packages"

[[input.files]]
path = "articles/linux/taskwarrior.rst"
url = "/taskwarrior.html"
title = "Taskwarrior"

[[input.files]]
path = "articles/puppet/puppet-3-upgrade.rst"
url = "/puppet-3-upgrade.html"
title = "Upgrade to puppet 3.3.0"

[[input.files]]
path = "articles/linux/print-scan.rst"
url = "/printing-scanning.html"
title = "Command line printing & scanning"

[[input.files]]
path = "articles/linux/software-raid.rst"
url = "/raid.html"
title = "CentOS 6.4 software raid & LVM"

[[input.files]]
path = "articles/linux/hubot.rst"
url = "/hubot.html"
title = "Hubot, the github chat automated bot"

[[input.files]]
path = "articles/linux/chromium-eid.md"
url = "/chromium-eid.html"
title = "Chromium eid"

[[input.files]]
path = "articles/linux/ratpoison.rst"
url = "/ratpoison.html"
title = "Ratpoison window manager"

[[input.files]]
path = "articles/linux/conky-colors.rst"
url = "/conky-colors.html"
title = "Conky-colors"

[[input.files]]
path = "articles/linux/tracks.rst"
url = "/tracks.html"
title = "Tracks"

[[input.files]]
path = "articles/linux/irssi-bitlbee-channel.rst"
url = "/irssi-bitlbee-channel.html"
title = "Irssi bitlbee channel"

[[input.files]]
path = "articles/android/gtalksms.rst"
url = "/gtalksms.html"
title = "GTalkSMS mobile alerting through xmpp protocol"

[[input.files]]
path = "articles/linux/selinux.rst"
url = "/selinux.html"
title = "Lighttpd change tcp port in CentOS"

[[input.files]]
path = "articles/linux/dropbox.rst"
url = "/dropbox.html"
title = "Dropbox"

[[input.files]]
path = "articles/puppet/puppet-revoked-certificate.rst"
url = "/puppet-revoked-certificate.rst.html"
title = "Puppet sslv3 alert certificate revoked"

[[input.files]]
path = "articles/linux/icinga-checks.rst"
url = "/icinga-checks.html"
title = "Writing customized icinga checks"

[[input.files]]
path = "articles/linux/sms-server.rst"
url = "/sms-server.html"
title = "SMS server using CentOS, kannel and playsms"

[[input.files]]
path = "articles/linux/lacie-networkspace-2.rst"
url = "/lacie-networkspace-2.html"
title = "SSH acces on Lacie Network Space 2"

[[input.files]]
path = "articles/linux/rpm-package.rst"
url = "/rpm-package.html"
title = "Create and distribute .rpm package"

[[input.files]]
path = "articles/puppet/puppet-mumble.rst"
url = "/puppet-mumble.html"
title = "Puppet module mumble-server"

[[input.files]]
path = "articles/networking/cisco-3G.rst"
url = "/cisco-3g.html"
title = "Cisco HWIC 3G configuration to 2G"

[[input.files]]
path = "articles/networking/bgp-default-route.rst"
url = "/bgp-default-route.html"
title = "BGP announcing default route"

[[input.files]]
path = "articles/apple/apple-linux-remote.rst"
url = "/apple-linux-remote.html"
title = "Apple remote (A1156) - MacBook Pro 3.1 & Ubuntu 10.04"

[[input.files]]
path = "articles/linux/symbolic-links.rst"
url = "/symbolic-links.html"
title = "Symbolic linux links"

[[input.files]]
path = "articles/security/web-permissions.rst"
url = "/web-permissions.html"
title = "Permissions website"

[[input.files]]
path = "articles/linux/conky.rst"
url = "/conky.html"
title = "Conky"

[[input.files]]
path = "articles/php/birthday-script.rst"
url = "/birthday-script.html"
title = "Showing birthdays using php"
